spring.application.name=common-library
server.port=8089
spring.datasource.url=jdbc:mysql://localhost:3306/outboxservcie?sslmode=require
spring.datasource.username=root
spring.datasource.password=bunty
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver



spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

spring.mail.host=smtp.gmail.com
spring.mail.username=ponn dxid wcwl tqxc
spring.mail.password=arvinderpalsingh2321@gmail.com
spring.mail.properties.mail.smtp.auth=true
spring.mail.port=587
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com